In [1]:
import pandas as pd
from scipy.io import arff
import requests
from utils import describe as des

Download data from the following public data set and save as a dataframe

https://www.openml.org/search?type=data&status=active&id=42175

In [2]:
url = "https://www.openml.org/data/download/21756045/dataset"
output_file = "../data/dataset.arff"

response = requests.get(url)
response.raise_for_status()

with open(output_file, "wb") as file:
    file.write(response.content)

In [3]:
data, metadata = arff.loadarff("../data/dataset.arff")

df = pd.DataFrame(data)

# Convert byte-string columns to regular strings
for column in df.select_dtypes(include="object").columns:
    df[column] = df[column].str.decode("utf-8")

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
df.shape

(284807, 31)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  float64
dtypes: float64(31)
memory usage: 67.4 MB

In [7]:
df.to_pickle("../data/data_00.pkl")

In [8]:
import hashlib

with open("../data/data_00.pkl", "rb") as file:
    file_hash = hashlib.sha256(file.read()).hexdigest()

print(file_hash)

b4e22b9304f7f0ab8d0aa0415f8cd69e79f43804ec3cb1f1b8ed33d6ee28cc5d

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
# Replace "target" with your target column
train_df, test_df = train_test_split(
    df,
    test_size=0.4,
    random_state=42,
    stratify=df["Class"]
)

In [11]:
pd.set_option("display.max_rows", None)

In [12]:
des.compare_datasets(train_df,test_df, 'Class')

               train          test  percent_difference
Time    94939.372885  94625.590162           -0.330509
V1          0.001974     -0.002961         -249.999561
V2         -0.004446      0.006669         -249.999561
V3         -0.002487      0.003731         -249.999561
V4          0.000112     -0.000167         -249.999561
V5          0.000407     -0.000611         -249.999561
V6         -0.000793      0.001189         -249.999561
V7         -0.001779      0.002669         -249.999561
V8         -0.000143      0.000214         -249.999561
V9          0.003307     -0.004961         -249.999561
V10        -0.000142      0.000213         -249.999561
V11        -0.002574      0.003861         -249.999561
V12         0.000254     -0.000381         -249.999561
V13        -0.003109      0.004664         -249.999561
V14        -0.000655      0.000983         -249.999561
V15         0.000220     -0.000330         -249.999561
V16        -0.001519      0.002278         -249.999561
V17         0.000154     -0.000231         -249.999561
V18        -0.000699      0.001048         -249.999561
V19         0.000474     -0.000711         -249.999561
V20        -0.001047      0.001571         -249.999561
V21         0.001404     -0.002106         -249.999561
V22         0.000342     -0.000513         -249.999561
V23         0.000642     -0.000962         -249.999561
V24         0.000264     -0.000396         -249.999561
V25        -0.000904      0.001356         -249.999561
V26         0.000250     -0.000375         -249.999561
V27        -0.000501      0.000751         -249.999561
V28         0.000121     -0.000182         -249.999561
Amount     88.429408     88.229936           -0.225573

In [13]:
pd.reset_option("display.max_rows")

In [14]:
train_df.to_pickle("../data/train_df.pkl")
test_df.to_pickle("../data/test_df.pkl")